{{/*
Copyright (C) 2025 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stia.trafficAgent.fullname" . }}
  labels:
    {{- include "stia.labels" . | nindent 4 }}
    app.kubernetes.io/component: traffic-agent
spec:
  type: {{ .Values.trafficAgent.service.type }}
  ports:
    - name: backend
      port: {{ .Values.trafficAgent.service.backendPort }}
      targetPort: 8081
      protocol: TCP
    - name: ui
      port: {{ .Values.trafficAgent.service.uiPort }}
      targetPort: 7860
      protocol: TCP
  selector:
    app: {{ include "stia.trafficAgent.fullname" . }}
